name: Publish TelegramgBot

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: BuddyLanguageTG
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ vars.APP_DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ./src/presentation/BuddyLanguage.TelegramBot/BuddyLanguage.TelegramBot.csproj

      - name: Build
        run: dotnet build ./src/presentation/BuddyLanguage.TelegramBot/BuddyLanguage.TelegramBot.csproj --configuration Release --no-restore --os linux-x64

      - name: Publish
        run: dotnet publish ./src/presentation/BuddyLanguage.TelegramBot/BuddyLanguage.TelegramBot.csproj --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' --os linux-x64

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_TGBOT_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
